### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Cin316** [mohamede1945/AssertionsTestingExample#1]
This code is great, but without a license, it's unclear what people who use the code should do when using it.  Adding a license would free people who use your code from having to worry about copyright litigation, and would give people a chance to give you credit for your work.

Adding a license is pretty easy, too.  This website will give you all of the details: http://www.addalicense.com/

**Comment by mohamede1945** [comment]
Thanks a lot for mentioning that. I've added a license to the project.
