### ISSUE TITLE
how to use from objective-c?

### ISSUE THREAD

**Issue by EXC-BAD-ACCESS** [mohamede1945/AssertionsTestingExample#3]
i have a swift method which calls assertionFailure and i need to test that method with a swift test AND an Obj-C test.  The swift test works perfectly but i cannot figure out how to call it from Obj-C.

it doesn't appear that swift is adding the method definitions into any kind of AssertionsTests-Swift.h file so i get "no such selector" errors at compile time. 

 i tried adding a new .h file like:
[XCTestCase+ProgrammerAssertions.h.txt](https://github.com/mohamede1945/AssertionsTestingExample/files/292363/XCTestCase.ProgrammerAssertions.h.txt)
which allows it to compile, but crashes at runtime.  

So I printed out all the methods on the Test class with:
[NSObject+Assertions.swift.txt](https://github.com/mohamede1945/AssertionsTestingExample/files/292361/NSObject.Assertions.swift.txt)
and sure enough it doesn't print expectAssertionFailure anywhere

but again the swift version of the test runs fine, so the methods are certainly there (further evidenced by an `nm AssertTests | grep expectAssertionFailure`)

perhaps there's a simpler solution?  i believe i used to be able to capture this sort of thing within an objc class using @try{}/@catch, but when i try that it crashes [here](https://github.com/mohamede1945/AssertionsTestingExample/blob/ad9dcc8d832bf4261dfd01ea9dbdf5d15962ec46/Assertions/ProgrammerAssertions.swift#L56)

**Comment by EXC-BAD-ACCESS** [comment]
i've figured out that the issue is that StaticString is not available within Obj-C...

**Comment by mohamede1945** [comment]
Glad it is working for you.
