### ISSUE TITLE
Add Swift 3 Support

### ISSUE THREAD

**Issue by Cin316** [mohamede1945/AssertionsTestingExample#4]
This module needs changes in order to support Swift 3.  I might try and figure out how to adapt it.  If I do, I'll add a pull request.

@mohamede1945 If you could take a look at adding Swift 3 support to the module, you could probably get it done quicker than I could

**Comment by mihaicris** [comment]
I have also tried to convert the code to Swift 3.1.  Unfortunatelly, I couldn't fix these errors:

AssertionsTests/XCTestCase+ProgrammerAssertions.swift:126:31: Cannot convert value of type 'Void' (aka '()') to closure result type 'Never'

AssertionsTests/XCTestCase+ProgrammerAssertions.swift:45:17: Closure use of non-escaping parameter 'caller' may allow it to escape

**Comment by mohamede1945** [comment]
This library is deprecated as it is not the best way to test assertions. You can use https://github.com/mattgallagher/CwlPreconditionTesting instead.
